name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install cc65
      run: |
        sudo apt-get update
        sudo apt-get install cc65

    - name: Build using cc65
      working-directory: ${{github.workspace}}
      run: USE_LOCAL_CC65=1 make -f Makefile_cc65 all
    
    - name: Install llvm-mos-sdk
      working-directory: ${{github.workspace}}
      run: |
        wget https://github.com/llvm-mos/llvm-mos-sdk/releases/latest/download/llvm-mos-linux.tar.xz
        tar xf llvm-mos-linux.tar.xz
        
    - name: Build using clang
      working-directory: ${{github.workspace}}
      run: |
        cmake -DCMAKE_PREFIX_PATH=llvm-mos -B build/ .
        cd build/
        make
